### ISSUE TITLE
Experiment with relativistic hinge-loss 

### ISSUE THREAD

**Issue by akanimax** [AlexiaJM/RelativisticGAN#13]
Hi @AlexiaJM,

I ran an experiment on my proposed **fagan** (full attention GAN) architecture using the relativistic version of the hinge-loss as proposed in this work of yours.
The details of the experiment are here -> [https://github.com/akanimax/fagan#relativistic-hinge-gan-loss-experiment](https://github.com/akanimax/fagan#relativistic-hinge-gan-loss-experiment). Could you provide your insights about the results. Are these as expected? Any help would be great.
Thank you!

Best regards,
@akanimax

**Comment by AlexiaJM** [comment]
Hi Animesh,

I don't have the experience with CELEBA to tell you if anything could be done to improve the quality of results. Implementation-wise, everything seems good. The discriminator is dominating hence why it's loss is so low, but that's okay since relativistim works as well even when the discriminator dominates.

Personally I re-sample from real data in the generator step ("images = batch.to(self.device)"), I dunno if it's helpful. You could try and see if it improve things or not.

You might want to give relativistic LSGAN a try too, it's pretty good.

Aleixa

**Comment by akanimax** [comment]
Hi Alexia,

I tried sending an email to you at `martineau@mail.mcgill.ca` (email given in your personal site), but it was undelivered. Could you please share your email id with me? 

Best regards,
Animesh

**Comment by AlexiaJM** [comment]
Email is alexia.jolicoeur-martineau@mail.mcgill.ca
