### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Ahalang** [AlexiaJM/RelativisticGAN#17]
Could you tell me how to change the dataset?the dataset of  CelebA is OK? Thank you

**Comment by AlexiaJM** [comment]
change this parameter to your other dataset:
parser.add_argument('--input_folder', default='/home/alexia/Datasets/Meow_64x64', help='input folder')

Make sure that you do not write --CIFAR10 True, since it will bypass your current input_folder.

This version doesn't have a crop parameter, but for CelebA, you might want to centercrop, if so then :

you can replace 

trans = transf.Compose([
	transf.Resize((param.image_size, param.image_size)),
	# This makes it into [0,1]
	transf.ToTensor(),
	# This makes it into [-1,1]
	transf.Normalize(mean = [0.5, 0.5, 0.5], std = [0.5, 0.5, 0.5])
])

with

trans = transf.Compose([
	transf.CenterCrop(param.centercrop),
	transf.Resize((param.image_size, param.image_size)),
	# This makes it into [0,1]
	transf.ToTensor(),
	# This makes it into [-1,1]
	transf.Normalize(mean = [0.5, 0.5, 0.5], std = [0.5, 0.5, 0.5])
])

and add in the beginning

parser.add_argument('--centercrop', type=int, default=0, help="If not 0, CenterCrop with specified number the images")

**Comment by AlexiaJM** [comment]
Btw, this more recent version has crop:
https://github.com/AlexiaJM/relativistic-f-divergences/blob/master/GAN.py

**Comment by AlexiaJM** [comment]
and code for CelebA too https://github.com/AlexiaJM/relativistic-f-divergences/blob/master/experiments.sh, so you might prefer working directly on this newer version:

**Comment by Ahalang** [comment]
Thanks for your quick response.
